joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

rear_right_velocity_controller:
  type: "velocity_controllers/JointVelocityController"
  joint: right_back_wheel_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}
rear_left_velocity_controller:
  type: "velocity_controllers/JointVelocityController"
  joint: left_back_wheel_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}
front_right_velocity_controller:
  type: "velocity_controllers/JointVelocityController"
  joint: right_front_wheel_to_bridge
  pid: {p: 100.0, i: 0.01, d: 10.0}
front_left_velocity_controller:
  type: "velocity_controllers/JointVelocityController"
  joint: left_front_wheel_to_bridge
  pid: {p: 100.0, i: 0.01, d: 10.0}
right_bridge_position_controller:
  type: "effort_controllers/JointPositionController"
  joint: right_bridge_to_bridge
  pid: {p: 4.0, i: 2.0, d: 1.0}
left_bridge_position_controller:
  type: "effort_controllers/JointPositionController"
  joint: left_bridge_to_bridge
  pid: {p: 4.0, i: 2.0, d: 1.0}

gazebo_ros_control:
 pid_gains:
   right_back_wheel_joint:
     p: 10000.0
     i: 0.5
     d: 0.0
   left_back_wheel_joint:
     p: 1.0
     i: 0.5
     d: 0.0
   right_front_wheel_to_bridge:
     p: 1.0
     i: 0.5
     d: 0.0
   left_front_wheel_to_bridge:
     p: 1.0
     i: 0.5
     d: 0.0
